apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      service: reverseproxy
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: 9674007/reverseproxy:v3
        name: reverseproxy
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "100Mi"
            cpu: "350m"
          limits:
            memory: "1024Mi"
            cpu: "700m"       
        ports:
        - containerPort: 8080
      restartPolicy: Always